=== swrd1337/cs-projects/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="sheets">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="student" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="personal_data" />
                <xs:element maxOccurs="unbounded" ref="studies" />
                <xs:element ref="domains" />
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer" />
        </xs:complexType>
    </xs:element>
    <xs:element name="personal_data">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="full_name" />
                <xs:element ref="initials" />
                <xs:element ref="cnp" />
                <xs:element ref="birthday" />
                <xs:element ref="birth_place" />
                <xs:element ref="gender" />
                <xs:element ref="address" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="full_name">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="first_name" />
                <xs:element ref="last_name" />
            </xs:sequence>
            <xs:attribute name="type" use="required" type="xs:NCName" />
        </xs:complexType>
    </xs:element>
    <xs:element name="first_name" type="xs:NCName" />
    <xs:element name="last_name" type="xs:NCName" />
    <xs:element name="initials" type="xs:NCName" />
    <xs:element name="cnp" type="xs:integer" />
    <xs:element name="birthday" type="xs:NMTOKEN" />
    <xs:element name="birth_place" type="xs:NCName" />
    <xs:element name="gender" type="xs:NCName" />
    <xs:element name="address" type="xs:string" />
    <xs:element name="studies">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element ref="institue_name" />
                <xs:element ref="contry" />
                <xs:element ref="city" />
                <xs:element ref="degree" />
                <xs:element ref="end_year" />
                <xs:element ref="score" />
            </xs:sequence>
            <xs:attribute name="type" use="required" type="xs:NCName" />
        </xs:complexType>
    </xs:element>
    <xs:element name="institue_name" type="xs:string" />
    <xs:element name="contry" type="xs:NCName" />
    <xs:element name="city" type="xs:NCName" />
    <xs:element name="degree" type="xs:NCName" />
    <xs:element name="end_year" type="xs:integer" />
    <xs:element name="score" type="xs:integer" />
    <xs:element name="domains">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="name" type="xs:string" />
</xs:schema>

=== swrd1337/cs-projects/xml/sheets.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- <!DOCTYPE sheets SYSTEM "validation.dtd">
<sheets> -->
<sheets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <student id="1">
        <personal_data>
            <full_name type="original">
                <first_name>John</first_name>
                <last_name>Doe</last_name>
            </full_name>
            <full_name type="actual">
                <first_name>John</first_name>
                <last_name>Doe</last_name>
            </full_name>
            <initials>I.</initials>
            <cnp>111111111111</cnp>
            <birthday>11.04.1994</birthday>
            <birth_place>Somewhere</birth_place>
            <gender>M.</gender>
            <address>Str. Freedom</address>
        </personal_data>
        <studies type="school">
            <institue_name>School</institue_name>
            <contry>Moldova</contry>
            <city>Chisinau</city>
            <degree>Bachelor</degree>
            <end_year>2012</end_year>
            <score>10</score>
        </studies>
        <studies type="university"/>
        <domains>
            <name>Computer Science</name>
        </domains>
    </student>
    <student id="1">
        <personal_data>
            <full_name type="original">
                <first_name>John</first_name>
                <last_name>Doe</last_name>
            </full_name>
            <full_name type="actual">
                <first_name>John</first_name>
                <last_name>Doe</last_name>
            </full_name>
            <initials>I.</initials>
            <cnp>111111111111</cnp>
            <birthday>11.04.1994</birthday>
            <birth_place>Somewhere</birth_place>
            <gender>M.</gender>
            <address>Str. Freedom</address>
        </personal_data>
        <studies type="school">
            <institue_name>School</institue_name>
            <contry>Moldova</contry>
            <city>Chisinau</city>
            <degree>Bachelor</degree>
            <end_year>2012</end_year>
            <score>10</score>
        </studies>
        <studies type="university">
            <institue_name>Local University</institue_name>
            <contry>Moldova</contry>
            <city>Chisinau</city>
            <degree>Graduate</degree>
            <end_year>2015</end_year>
            <score>10</score>
        </studies>
        <domains>
            <name>Computer Science</name>
        </domains>
    </student>
</sheets>
